spring.application.name=api
server.port=9001

#boot2.7.x对swagger的支持
spring.mvc.pathmatch.matching-strategy=ant_path_matcher

spring.session.store-type=redis
server.servlet.session.timeout=36000

spring.datasource.type=com.alibaba.druid.pool.DruidDataSource
spring.datasource.driver-class-name=com.mysql.jdbc.Driver
spring.datasource.url=jdbc:mysql://192.168.64.100:3306/prize?useUnicode=true&characterEncoding=utf-8
spring.datasource.username=root
spring.datasource.password=root

mybatis.mapper-locations=classpath:mapper/*.xml
logging.level.com.itheima.prize=error
logging.level.com.itheima.prize.commons.db.mapper=error
#日志对QPS性能影响极大，测试或生产环境时关闭，或只保留error
#I/O 瓶颈：你的日志级别是 debug，且开启了 mapper 的 debug（即打印 SQL 语句）。这意味着每一个 HTTP 请求都会导致控制台输出多条 SQL 语句和参数信息。写控制台（Console）是同步 I/O 操作，非常慢，会直接阻塞工作线程。
#同步锁竞争：日志框架在输出到控制台时通常有锁机制。当 QPS 很高时，成百上千个线程争抢输出日志，会导致严重的线程阻塞。
#CPU 消耗：频繁的字符串拼接、格式化参数、序列化对象都会消耗 CPU 资源。
#优化建议
#在压测或生产环境中，请务必关闭 DEBUG 日志，只保留 INFO 或 ERROR。
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=GMT+8

spring.rabbitmq.host=192.168.64.100
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.rabbitmq.virtual-host=/

spring.redis.host=192.168.64.100
spring.redis.port=6379

server.tomcat.threads.max=500
server.tomcat.accept-count=100
